ColumnMaps:
 tenantId: [ch.chandigarh]
 columnConfig:
   - applicationType: PETNOC
     status: [APPROVED]
     roles: [CITIZEN]
     emailSubject: Application Approved
     template: Dear Applicant,<br/><p>Your application id - [:applicationId:] for permission for keeping of Pets has been approved. Kindly visit the MMC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Your application id [:applicationId:] for permission for Keeping of Pets has been approved. Kindly visit the MMC Chandigarh portal for details.
     
   - applicationType: PETNOC
     status: [REJECTED]
     roles: [CITIZEN]
     emailSubject: Application Rejected
     template: Dear Applicant,<br/><p>Your application id - [:applicationId:] for permission for keeping of Pets has been rejected. Kindly visit the MMC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Your application id [:applicationId:] for permission for Keeping of Pets has been rejected. Kindly visit the MMC Chandigarh portal for details.

   - applicationType: PETNOC
     status: [PAID]
     roles: [CITIZEN]
     emailSubject: Application Submitted
     template: Dear Applicant,<br/><p>Thank you for submitting online application for permission of keeping pets at Chandigarh Municipal Corporation portal. Your Application id - [:applicationId:] .You can log on to the MCC Chandigarh portal for further details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, Your application ID - [:applicationId:] has been received for permission of Keeping pets. Please login to MCC portal for details.
   
   - applicationType: PETNOC
     status: [REASSIGN]
     roles: [CITIZEN]
     emailSubject: Application Required Information
     template: Dear Applicant,<br/><p>You are requested to provide additional clarification as requested by the Department against your application id [:applicationId:] for permission of Keeping pets. Please login to MCC portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, you are requested to provide clarification for your application id [:applicationId:] for permission of Keeping pets. Please visit MCC portal for details.

   - applicationType: SELLMEATNOC
     status: [INITIATED]
     roles: [CITIZEN]
     emailSubject: Application Submitted
     template: Dear Applicant,<br/><p>Thank you for submitting online application for permission to sell meat at Chandigarh Municipal Corporation portal.Your Application id - [:applicationId:] .You can log on to the MCC Chandigarh portal for further details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, Your application ID - [:applicationId:] has been received for permission to sell meat. Please login to MCC portal for details.

   - applicationType: SELLMEATNOC
     status: [APPROVED]
     roles: [CITIZEN]
     emailSubject: Application Approved
     template: Dear Applicant,<br/><p>Your application id - [:applicationId:]  for permission to sell meat has been approved. Kindly visit the MMC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, Your application ID - [:applicationId:]  for permission to sell meat has been approved. Kindly visit the MMC Chandigarh portal for details.

   - applicationType: SELLMEATNOC
     status: [REJECTED]
     roles: [CITIZEN]
     emailSubject: Application Rejected
     template: Dear Applicant,<br/><p>Your application id - [:applicationId:]  for permission to sell meat has been rejected. Kindly visit the MMC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, Your application ID - [:applicationId:]  for permission to sell meat has been  rejected. Kindly visit the MMC Chandigarh portal for details..
     
   - applicationType: SELLMEATNOC
     status: [REASSIGN]
     roles: [CITIZEN]
     emailSubject: Application Required Information
     template: Dear Applicant,<br/><p>You are requested to provide additional clarification as requested by the Department against your application id [:applicationId:] for permission to sell meat. Please login to MCC portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, you are requested to provide clarification for your application id [:applicationId:] for permission to sell meat. Please visit MCC portal for details.
 
   - applicationType: ROADCUTNOC
     status: [INITIATED]
     roles: [CITIZEN]
     emailSubject: Application Submitted
     template: Dear Applicant,<br/><p>Thank you for submitting online application for permission for Road Cut at Chandigarh Municipal Corporation portal. Your Application id - [:applicationId:] .You can log on to the MCC Chandigarh portal for further details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, Your application ID - [:applicationId:] has been received for permission for Road Cut. Please login to MCC portal for details

   - applicationType: ROADCUTNOC
     status: [REASSIGN]
     roles: [CITIZEN]
     emailSubject: Application Required Information
     template: Dear Applicant,<br/><p>You are requested to provide additional clarification as requested by the Department against your application ID - [:applicationId:] for Permission for Road Cut. Please login to MCC portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate:  Dear Applicant, you are requested to provide clarification for your application ID - [:applicationId:] for Permission for Road Cut. Please visit MCC portal for details.

   - applicationType: ROADCUTNOC
     status: [APPROVED]
     roles: [CITIZEN]
     emailSubject: Application Approved
     template: Dear Applicant,<br/><p>Your application ID - [:applicationId:] for Permission for Road Cut is under processing. Kindly pay the requisite Road cut charges amounting to Rs. [:fees:] including GST and bank guarantee by visiting MMC Chandigarh portal.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, as per your application ID - [:applicationId:] for road cut permission is under processing, Kindly pay Rs. [:fees:] at MCC Chandigarh portal for approval.

   - applicationType: ROADCUTNOC
     status: [REJECTED]
     roles: [CITIZEN]
     emailSubject: Application Rejected
     template: Dear Applicant,<br/><p> Dear Applicant<br/><p>Your application ID - [:applicationId:] for Permission for Road Cut is under processing. Kindly pay the requisite Road cut charges amounting to Rs. [:fees:] including GST and bank guarantee by visiting MMC Chandigarh portal.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, as per your application ID - [:applicationId:] for road cut permission is under processing, Kindly pay Rs. [:fees:] at MCC Chandigarh portal for approval.
 
   - applicationType: ADVERTISEMENTNOC
     status: [UPDATE]
     roles: [JEX,SUPERINTENDENT,COMMISSIONER]
     emailSubject: Revised Fees For Advertisement 
     template: Respected Sir/ Mam,<br/><p>This is to inform you that advertisement fees has been revised in the Chandigarh Municipality portal. Please visit MCC Chandigarh portal for further details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: ""
     
   - applicationType: ADVERTISEMENTNOC
     status: [APPROVED]
     roles: [CITIZEN]
     emailSubject: Application Approved
     template: Dear Applicant,<br/><p>Your application id - [:applicationId:]  for Permission for Advertisement has been approved. Kindly visit the MMC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, Your application id [:applicationId:] for Permission for Advertisement has been approved. Kindly visit the MMC Chandigarh portal for details.
   
   - applicationType: ADVERTISEMENTNOC
     status: [REJECTED]
     roles: [CITIZEN]
     emailSubject: Application Rejected
     template: Dear Applicant<br/><p>, Your application id - [:applicationId:]  for Permission for Advertisement has been rejected. Kindly visit the MMC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, Your application id [:applicationId:] for Permission for Advertisement has been rejected. Kindly visit the MMC Chandigarh portal for details. 

   - applicationType: ADVERTISEMENTNOC
     status: [PAID,INITIATEDEXC]
     roles: [CITIZEN]
     emailSubject: Application Submitted
     template: Dear Applicant,<br/><p>Thank you for submitting online application for Permission for Advertisement at Chandigarh Municipal Corporation portal. Your Application id - [:applicationId:] .You can log on to the MCC Chandigarh portal for further details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, Your application ID - [:applicationId:]  has been received for Permission for Advertisement. Please login to MCC portal for details.

   - applicationType: ADVERTISEMENTNOC
     status: [REASSIGN]
     roles: [CITIZEN]
     emailSubject: Application Required Information
     template: Dear Applicant,<br/><p>You are requested to provide additional clarification as requested by the Department against your application id [:applicationId:] for Permission for Advertisement. Please login to MCC portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, you are requested to provide clarification for your application id [:applicationId:]  for Permission for Advertisement. Please visit MCC portal for details

   - applicationType: ADVERTISEMENTNOC
     status: [WITHDRAW,WITHDRAWAFTERAPRROVAL]
     roles: [CITIZEN]
     emailSubject: Application Withdraw Information
     template: Dear Applicant,<br/><p>Withdrawal request has been submitted for your application ID - [:applicationId:] for Permission for Advertisement. Refund amount is in under processing if any. Kindly visit the MMC Chandigarh portal for details.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: Dear Applicant, Withdrawal request has been submitted for your application ID - [:applicationId:] for Permission for Advertisement. Kindly visit the MMC Chandigarh portal for details.

   - applicationType: ADVERTISEMENTNOC
     status: [WITHDRAW,WITHDRAWAFTERAPRROVAL]
     roles: [COMMISSIONER]
     emailSubject: Application Withdraw Information
     template: Respected Sir/ Mam,<br/><p>This is to inform you that Application id -[:applicationId:] for permission of advertisement has been withdrawal by the applicant.</p><br/>Regards,<br/>Portal Administrator (MCC Chandigarh)
     smsTemplate: ""
